import type { Settings, Product, Banner, Testimonial } from './types';

export const DEFAULT_SETTINGS: Omit<Settings, 'id' | 'updated_at'> = {
  site_name: 'Tropical Herbs',
  whatsapp_number: '27635987328',
  phone_display: '+27 63 598 7328',
  location: 'Johannesburg, South Africa',
  hero_badge: 'Traditional Healing · Trusted for Generations',
  hero_title_line1: 'Tropical',
  hero_title_line2: 'Herbal Products',
  hero_subtitle:
    'Discover the healing power of nature with our handcrafted tropical herbal remedies. Rooted in ancestral wisdom, prepared with pure natural ingredients for your wellbeing.',
  hero_image_url: 'https://picsum.photos/seed/tropicalhero/1920/1080',
  about_image_url: 'https://picsum.photos/seed/tropicalherbs/600/700',
  about_title: 'Rooted in Tradition, Guided by Nature',
  about_paragraph1:
    'For over fifteen years, I have dedicated my life to the ancient art of traditional healing. My knowledge comes from generations of healers in my family, who passed down sacred formulas using the purest tropical herbs, roots, and natural remedies found across Africa.',
  about_paragraph2:
    'Every product is hand-prepared in small batches to preserve potency and authenticity. I believe true healing comes from nature — not synthetic chemicals. My mission is to bring the wisdom of traditional medicine to modern lives, helping thousands find natural relief and lasting wellness.',
  stat_products: '12+',
  stat_clients: '5000+',
  stat_years: '15+',
};

export const DEFAULT_PRODUCTS: Omit<Product, 'id' | 'created_at'>[] = [
  {
    name: 'Bee Green Tea',
    category: 'Detox & Cleansing',
    description: 'A powerful detox blend crafted from tropical green herbs and natural bee pollen extracts.',
    price: 'R150',
    image_url: 'https://picsum.photos/seed/beegreentea/400/400',
    benefits: ['Detoxifies the body', 'Boosts immunity', 'Rich in antioxidants', 'Improves digestion'],
    accent_color: '#22c55e',
    sort_order: 1,
    is_active: true,
  },
  {
    name: 'Kayamani Green Mix',
    category: 'Body Regulation',
    description: "Traditional formula that restores harmony to your body's natural systems and rhythms.",
    price: 'R180',
    image_url: 'https://picsum.photos/seed/kayamani/400/400',
    benefits: ['Regulates body systems', 'Restores natural balance', 'Supports organ function', 'Reduces inflammation'],
    accent_color: '#10b981',
    sort_order: 2,
    is_active: true,
  },
  {
    name: 'Moringa Vitality Blend',
    category: 'Energy & Strength',
    description: 'Superfood-powered blend from the miracle moringa tree for sustained natural energy.',
    price: 'R200',
    image_url: 'https://picsum.photos/seed/moringa/400/400',
    benefits: ['Boosts energy levels', 'Rich in vitamins & minerals', 'Supports brain function', 'Anti-aging properties'],
    accent_color: '#84cc16',
    sort_order: 3,
    is_active: true,
  },
  {
    name: 'Sleep Well Tonic',
    category: 'Sleep & Relaxation',
    description: 'Calming herbal tonic blended with traditional sleep herbs for restful, deep sleep.',
    price: 'R170',
    image_url: 'https://picsum.photos/seed/sleepwell/400/400',
    benefits: ['Promotes deep sleep', 'Reduces anxiety', 'Calms nervous system', 'Non-habit forming'],
    accent_color: '#6366f1',
    sort_order: 4,
    is_active: true,
  },
  {
    name: 'Blood Cleanser Formula',
    category: 'Blood Purification',
    description: 'Ancient blood purification formula using tropical roots and cleansing herbs.',
    price: 'R190',
    image_url: 'https://picsum.photos/seed/bloodcleanse/400/400',
    benefits: ['Purifies the blood', 'Improves circulation', 'Clears skin conditions', 'Supports liver health'],
    accent_color: '#ef4444',
    sort_order: 5,
    is_active: true,
  },
  {
    name: 'Joint & Bone Relief',
    category: 'Pain & Inflammation',
    description: 'Traditional anti-inflammatory blend for joint mobility and bone strength.',
    price: 'R220',
    image_url: 'https://picsum.photos/seed/jointbone/400/400',
    benefits: ['Reduces joint pain', 'Fights inflammation', 'Improves mobility', 'Strengthens bones'],
    accent_color: '#f59e0b',
    sort_order: 6,
    is_active: true,
  },
  {
    name: 'Fertility Boost Blend',
    category: 'Reproductive Health',
    description: 'Time-honored fertility formula passed down through generations of traditional healers.',
    price: 'R250',
    image_url: 'https://picsum.photos/seed/fertility/400/400',
    benefits: ['Supports fertility', 'Balances hormones', 'Improves reproductive health', 'Traditional formula'],
    accent_color: '#ec4899',
    sort_order: 7,
    is_active: true,
  },
  {
    name: 'Stomach Soothe Tea',
    category: 'Digestive Health',
    description: 'Gentle digestive tea brewed from soothing tropical herbs for stomach comfort.',
    price: 'R140',
    image_url: 'https://picsum.photos/seed/stomachsoothe/400/400',
    benefits: ['Soothes stomach pain', 'Reduces bloating', 'Aids digestion', 'Improves appetite'],
    accent_color: '#d97706',
    sort_order: 8,
    is_active: true,
  },
  {
    name: 'Immune Warrior Mix',
    category: 'Immune Support',
    description: 'Potent immune-boosting blend with traditional African medicinal herbs and roots.',
    price: 'R180',
    image_url: 'https://picsum.photos/seed/immunewarrior/400/400',
    benefits: ['Strengthens immunity', 'Fights infections', 'Reduces cold symptoms', 'Year-round protection'],
    accent_color: '#06b6d4',
    sort_order: 9,
    is_active: true,
  },
  {
    name: 'Sugar Balance Capsules',
    category: 'Blood Sugar Control',
    description: 'Natural blood sugar support using traditional herbs known for glycemic balance.',
    price: 'R210',
    image_url: 'https://picsum.photos/seed/sugarbalance/400/400',
    benefits: ['Regulates blood sugar', 'Supports pancreas', 'Reduces sugar cravings', 'Natural ingredients'],
    accent_color: '#8b5cf6',
    sort_order: 10,
    is_active: true,
  },
  {
    name: 'Stress Relief Elixir',
    category: 'Mental Wellness',
    description: 'Calming elixir for mental clarity and emotional balance using adaptogenic herbs.',
    price: 'R175',
    image_url: 'https://picsum.photos/seed/stressrelief/400/400',
    benefits: ['Reduces stress', 'Promotes calmness', 'Improves focus', 'Enhances mood'],
    accent_color: '#14b8a6',
    sort_order: 11,
    is_active: true,
  },
  {
    name: 'Skin Repair Oil',
    category: 'Skin Health',
    description: 'Nourishing topical oil infused with tropical botanicals for skin healing and repair.',
    price: 'R195',
    image_url: 'https://picsum.photos/seed/skinrepair/400/400',
    benefits: ['Repairs skin damage', 'Reduces scars', 'Anti-bacterial', 'Natural moisturizer'],
    accent_color: '#f472b6',
    sort_order: 12,
    is_active: true,
  },
];

export const DEFAULT_TESTIMONIALS: Omit<Testimonial, 'id'>[] = [
  { name: 'Thandi Mokoena', location: 'Johannesburg', rating: 5, text: 'The Bee Green Tea completely transformed my energy levels. I feel lighter, healthier, and more vibrant every day. Truly life-changing traditional medicine!', sort_order: 1, is_active: true },
  { name: 'Sipho Nkosi', location: 'Durban', rating: 5, text: 'After years of joint pain, the Joint & Bone Relief blend gave me my mobility back. I can walk without discomfort again. Thank you for this miracle formula.', sort_order: 2, is_active: true },
  { name: 'Lerato van der Merwe', location: 'Cape Town', rating: 5, text: 'Sleep Well Tonic is the only natural remedy that actually works for me. I fall asleep peacefully and wake up refreshed. No more restless nights!', sort_order: 3, is_active: true },
  { name: 'David Pretorius', location: 'Pretoria', rating: 5, text: 'The Moringa Vitality Blend keeps me energized throughout my busy workdays without any crash. Pure, natural power from traditional healing wisdom.', sort_order: 4, is_active: true },
  { name: 'Nomsa Dlamini', location: 'Soweto', rating: 5, text: 'My skin has never looked better since using the Skin Repair Oil. Scars are fading and my complexion glows naturally. Authentic herbal healing at its finest.', sort_order: 5, is_active: true },
  { name: 'James Pillay', location: 'Pietermaritzburg', rating: 5, text: 'The Immune Warrior Mix kept my whole family healthy through winter. Fast WhatsApp service and genuine care from a true traditional healer. Highly recommended!', sort_order: 6, is_active: true },
];

export const DEFAULT_BANNERS: Omit<Banner, 'id'>[] = [
  {
    type: 'promo',
    image_url: 'https://picsum.photos/seed/herbpromo1/1200/400',
    title: 'Free Consultation',
    subtitle: 'Message us on WhatsApp for personalized herbal advice',
    link_url: '',
    sort_order: 1,
    is_active: true,
  },
];
